/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xiabaike.algo.sort;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.xiabaike.algo.sort.MergeSort;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MergeSort_SSTest extends MergeSort_SSTest_scaffolding {
// allCoveredLines:[8, 11, 12, 15, 16, 18, 20, 21, 23, 27, 28, 29, 30, 31, 33, 34, 36, 41, 42, 44, 45, 48, 49, 51, 52]

  @Test(timeout = 4000)
  public void test_sort_0()  throws Throwable  {
      //caseID:e3c6109bb91ff21c04fd270f71454bb0
      //CoveredLines: [8, 11, 12, 15, 16, 18, 20, 21, 23, 27, 28, 29, 30, 31, 33, 34, 36, 41, 42, 44, 45, 48, 49, 51, 52]
      //Input_0_int[]: intArray0
      
      MergeSort mergeSort0 = new MergeSort();
      int[] intArray0 = new int[4];
      intArray0[0] = (-18);
      
      //Call method: sort
      mergeSort0.sort(intArray0);
      
      //Test Result Assert
      assertArrayEquals(new int[] {(-18), 0, 0, 0}, intArray0);
  }
}
