/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.xiabaike.algo.sort;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.xiabaike.algo.sort.QuickSort;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class QuickSort_SSTest extends QuickSort_SSTest_scaffolding {
// allCoveredLines:[8, 11, 12, 16, 17, 19, 20, 22, 24, 27, 29, 32, 33, 34, 35, 36, 37, 39, 40, 42, 43, 44, 46, 47, 50]

  @Test(timeout = 4000)
  public void test_sort_0()  throws Throwable  {
      //caseID:1d96cfa9266079b900b2b53c1c182477
      //CoveredLines: [8, 11, 12, 16, 17, 19, 20, 22, 24, 27, 29, 32, 33, 34, 35, 36, 37, 39, 40, 42, 43, 44, 46, 47, 50]
      //Input_0_int[]: intArray0
      
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[9];
      intArray0[0] = (-1);
      intArray0[4] = (-1);
      
      //Call method: sort
      quickSort0.sort(intArray0);
      
      //Test Result Assert
      assertArrayEquals(new int[] {(-1), (-1), 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test_sort_1()  throws Throwable  {
      //caseID:412b6ddc5e6159aec92d05774a8bdd96
      //CoveredLines: [8, 11, 12, 16, 17, 19, 20, 22, 24, 27, 29, 32, 33, 34, 35, 36, 37, 39, 40, 42, 43, 44, 46, 47, 50]
      //Input_0_int[]: intArray0
      
      QuickSort quickSort0 = new QuickSort();
      int[] intArray0 = new int[9];
      intArray0[1] = (-1);
      
      //Call method: sort
      quickSort0.sort(intArray0);
      
      //Test Result Assert
      assertArrayEquals(new int[] {(-1), 0, 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }
}
